#include "qizo.h"

#define LINE_MAX 128
#define HIST_MAX 8

extern void qizo_banner(void);
extern void qizo_calibrate(void);
extern u64 qizo_cycles_per_ms(void);
extern void qizo_idt_install(void);
extern void qizo_cpuinfo(void);
extern void qizo_memstat(void);
extern void qizo_console_color(u32 attr);
extern int qizo_console_vga(void);
extern u64 qizo_ticks_to_ms(u64 t);
extern u64 qizo_keyboard_irqs(void);
extern u64 qizo_bench_memcpy_cycles(size_t n, int mode);
extern void qizo_pause(void);

static char line[LINE_MAX];
static u32 len;
static char hist[HIST_MAX][LINE_MAX];
static u32 hist_count;

static void push_history(void)
{
	if (!len)
		return;
	qizo_memcpy(hist[hist_count % HIST_MAX], line, len + 1);
	hist_count++;
}

static void edit_line(int key)
{
	if (key == '\b') {
		if (len) {
			len--;
			line[len] = 0;
			qizo_puts("\b \b");
		}
		return;
	}
	if (key == '\t') {
		if (len + 6 < LINE_MAX) {
			qizo_memcpy(line + len, "help\0", 6);
			len += 5;
			qizo_puts("help");
		}
		return;
	}
	if (key < 32 || key > 126)
		return;
	if (len + 1 >= LINE_MAX)
		return;
	line[len++] = (char)key;
	line[len] = 0;
	qizo_putc((char)key);
}

static int word_eq(const char *a, const char *b)
{
	return qizo_strcasecmp(a, b) == 0;
}

static void microbench(void)
{
	u64 c0 = qizo_bench_memcpy_cycles(16, 0);
	u64 c1 = qizo_bench_memcpy_cycles(16, 1);
	u64 c2 = qizo_bench_memcpy_cycles(16, 2);
	u64 c3 = qizo_bench_memcpy_cycles(256, 0);
	u64 c4 = qizo_bench_memcpy_cycles(256, 1);

	qizo_printf("memcpy 16B   scalar %u  sse2 %u  rep %u\r\n", (u32)c0, (u32)c1, (u32)c2);
	qizo_printf("memcpy 256B  scalar %u  sse2 %u\r\n", (u32)c3, (u32)c4);
}

static void prompt(void)
{
	qizo_console_color(0x0A);
	qizo_puts("qizo");
	qizo_console_color(0x07);
	qizo_puts("> ");
}

static void help(void)
{
	qizo_puts("help            this list\r\n");
	qizo_puts("info            kernel and hardware summary\r\n");
	qizo_puts("cpu             cpu identity, features, clock\r\n");
	qizo_puts("mem             frame allocator state\r\n");
	qizo_puts("bench           memory bandwidth benchmark\r\n");
	qizo_puts("micro           small copy microbenchmarks\r\n");
	qizo_puts("ticks           uptime and interrupt counters\r\n");
	qizo_puts("speed           raw op timing\r\n");
	qizo_puts("about           project and license\r\n");
	qizo_puts("clear           wipe the screen\r\n");
	qizo_puts("reboot          reset the machine\r\n");
}

static void about(void)
{
	qizo_puts("qizo - an operating system written from scratch\r\n");
	qizo_puts("code and assets generated by Arena.ai Agent Mode\r\n");
	qizo_puts("maintainers: Seigh-sword (arunkumar), suripewepedi (surya)\r\n");
	qizo_puts("license: BSD-3-Clause\r\n");
}

static void speed(void)
{
	u64 t0, t1;
	u64 i;
	u64 acc = 0;
	volatile char buf[64];

	qizo_puts("timing 1e5 byte loops:\r\n");
	t0 = qizo_rdtsc();
	for (i = 0; i < 100000; i++) {
		buf[i & 63] = (char)i;
		acc += (u8)buf[i & 63];
	}
	t1 = qizo_rdtsc();
	qizo_printf("  store loop   %u cycles (%u per op)\r\n", (u32)(t1 - t0),
		    (u32)((t1 - t0) / 100000));
	qizo_printf("  checksum     %u\r\n", (u32)acc);
}

void qizo_shell(void)
{
	prompt();
	for (;;) {
		int c = qizo_kbd_get();

		if (c < 0) {
			qizo_pause();
			continue;
		}
		if (c == '\n') {
			char *cmd;
			char *arg;

			qizo_puts("\r\n");
			line[len] = 0;
			push_history();
			cmd = line;
			while (*cmd == ' ')
				cmd++;
			arg = cmd;
			while (*arg && *arg != ' ')
				arg++;
			if (*arg) {
				*arg = 0;
				arg++;
				while (*arg == ' ')
					arg++;
			}
			if (!*cmd) {
				prompt();
				continue;
			}
			if (word_eq(cmd, "help"))
				help();
			else if (word_eq(cmd, "info") || word_eq(cmd, "sysinfo"))
				qizo_sysinfo();
			else if (word_eq(cmd, "cpu"))
				qizo_cpuinfo();
			else if (word_eq(cmd, "mem") || word_eq(cmd, "free"))
				qizo_memstat();
			else if (word_eq(cmd, "bench"))
				qizo_bench();
			else if (word_eq(cmd, "micro"))
				microbench();
			else if (word_eq(cmd, "about"))
				about();
			else if (word_eq(cmd, "banner"))
				qizo_banner();
			else if (word_eq(cmd, "ticks")) {
				u64 t = qizo_ticks();

				qizo_printf("ticks %u  ms %u  kbd irq %u\r\n", (u32)t,
					    (u32)qizo_ticks_to_ms(t), (u32)qizo_keyboard_irqs());
			} else if (word_eq(cmd, "speed"))
				speed();
			else if (word_eq(cmd, "clear")) {
				qizo_clear();
			} else if (word_eq(cmd, "reboot")) {
				qizo_reboot();
			} else {
				qizo_puts("qizo: unknown command '");
				qizo_puts(cmd);
				qizo_puts("' (try help)\r\n");
			}
			len = 0;
			prompt();
			continue;
		}
		if (c == 0x03) {
			qizo_puts("^C\r\n");
			len = 0;
			prompt();
			continue;
		}
		edit_line(c);
	}
}
