import os
import re
import sys

FIELDS = [
    ("u32", "magic", "QIZO_BI_MAGIC"),
    ("u8", "drive", "QIZO_BI_DRIVE"),
    ("u8", "mode", "QIZO_BI_MODE"),
    ("u8", "err", "QIZO_BI_ERR"),
    ("u32", "blob_lba", "QIZO_BI_BLOB_LBA"),
    ("u32", "blob_sectors", "QIZO_BI_BLOB_SECTORS"),
    ("u32", "blob_crc", "QIZO_BI_BLOB_CRC"),
    ("u32", "blob_phys", "QIZO_BI_BLOB_PHYS"),
    ("u32", "blob_size", "QIZO_BI_BLOB_SIZE"),
    ("u32", "scratch", "QIZO_BI_SCRATCH"),
    ("u32", "ktext", "QIZO_BI_KTEXT"),
    ("u32", "kernel_size", "QIZO_BI_KERNEL_SIZE"),
    ("u32", "kernel_entry", "QIZO_BI_KERNEL_ENTRY"),
    ("u32", "kernel_total", "QIZO_BI_KERNEL_TOTAL"),
    ("u32", "kernel_bss", "QIZO_BI_KERNEL_BSS"),
    ("u32", "flags", "QIZO_BI_FLAGS"),
    ("u32", "cpus", "QIZO_BI_CPUS"),
    ("u32", "cpuid_max", "QIZO_BI_CPUID_MAX"),
    ("u8", "longmode", "QIZO_BI_LONGMODE"),
    ("u8", "a20", "QIZO_BI_A20"),
    ("e820arr", "map", "QIZO_BI_E820"),
    ("u32", "map_count", "QIZO_BI_E820_N"),
    ("u8arr16", "vendor", "QIZO_BI_VENDOR"),
    ("u8arr80", "brand", "QIZO_BI_BRAND"),
    ("u64", "total_ram", "QIZO_BI_TOTAL_RAM"),
]

E820 = [("u64", "base", 0), ("u64", "size", 8), ("u32", "type", 16), ("u32", "acpi", 20)]

SIZES = {"u8": 1, "u32": 4, "u64": 8, "u8arr16": 16, "u8arr80": 80}
TYPES = {"u8": "u8", "u32": "u32", "u64": "u64"}
ARRS = {"u8arr16": ("u8", 16), "u8arr80": ("u8", 80)}


def parse_inc(path):
    vals = {}
    pat = re.compile(r"^\s*\.set\s+(\w+)\s*,\s*(.+?)\s*$")
    for line in open(path):
        m = pat.match(line)
        if not m:
            continue
        name, expr = m.group(1), m.group(2)
        try:
            vals[name] = eval(expr, dict(vals))
        except Exception:
            vals[name] = None
    return vals


def decl(t, name, v=None):
    if t == "e820arr":
        return "struct qizo_e820 %s[%d];" % (name, v["QIZO_E820_MAX"])
    if t in ARRS:
        base, n = ARRS[t]
        return "%s %s[%d];" % (base, name, n)
    return "%s %s;" % (t, name)


def emit(inc_path, out_path):
    v = parse_inc(inc_path)
    missing = [sym for _, _, sym in FIELDS if v.get(sym) is None]
    for extra in ("QIZO_BI_E820", "QIZO_BI_SIZE", "QIZO_E820_MAX", "QIZO_E820_ENT",
                  "QIZO_KTEXT", "QIZO_BOOTINFO", "QIZO_SCRATCH", "QIZO_BLOB_MAX"):
        if v.get(extra) is None:
            missing.append(extra)
    if missing:
        raise SystemExit("qizo: unresolved bootinfo symbols: %s" % ", ".join(missing))
    lines = []
    lines.append("#pragma once")
    lines.append("/* generated by tools/qizoartifacts/qizobootinfo.py from boot/qizoboot.inc */")
    for sym in sorted(k for k in v if k.startswith("QIZO_")):
        if v[sym] is None:
            continue
        lines.append("#define %s 0x%X" % (sym, v[sym]))
    lines.append("")
    lines.append("struct qizo_e820 {")
    for t, name, off in E820:
        lines.append("\t" + decl(t, name))
    lines.append("} __attribute__((packed));")
    for t, name, off in E820:
        lines.append("_Static_assert(__builtin_offsetof(struct qizo_e820, %s) == %d, \"e820 %s\");"
                     % (name, off, name))
    lines.append("_Static_assert(sizeof(struct qizo_e820) == QIZO_E820_ENT, \"e820 size\");")
    lines.append("")
    lines.append("struct qizo_bootinfo {")
    cur = 0
    for t, name, sym in FIELDS:
        off = v[sym]
        if off < cur:
            raise SystemExit("qizo: bootinfo field %s overlaps previous field" % name)
        if off > cur:
            lines.append("\tu8 pad_%s[%d];" % (name, off - cur))
        lines.append("\t" + decl(t, name, v))
        if t == "e820arr":
            cur = off + v["QIZO_E820_ENT"] * v["QIZO_E820_MAX"]
        else:
            cur = off + SIZES[t]
    lines.append("} __attribute__((packed));")
    for t, name, sym in FIELDS:
        lines.append("_Static_assert(__builtin_offsetof(struct qizo_bootinfo, %s) == %s, \"%s\");"
                     % (name, sym, name))
    lines.append("_Static_assert(sizeof(struct qizo_bootinfo) <= QIZO_BI_SIZE, \"bootinfo size\");")
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    open(out_path, "w").write("\n".join(lines) + "\n")
    return len(lines)


if __name__ == "__main__":
    inc, out = sys.argv[1], sys.argv[2]
    n = emit(inc, out)
    print("bootinfo header: %d lines from %s" % (n, os.path.basename(inc)))
